### ISSUE TITLE
`indexPathForAsset` result is not correct 

### ISSUE THREAD

**Issue by fromkk** [1amageek/PHFetchedResultsController#3]
item and section is reversed.

https://github.com/1amageek/PHFetchedResultsController/blob/master/PHFetchedResultsController/PHFetchedResultsController.m#L639

correct is `return [NSIndexPath indexPathForItem:index inSection:section];`

**Comment by 1amageek** [comment]
You can use version 2.2.3

**Comment by fromkk** [comment]
thank you!
